name: Run Tests

on: [push, pull_request]

jobs:
  runtests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/quattor/quattor-test-container:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: run tests
      run: |
        # we have to run as a non-root user to pass the spma tests
        # secondly, we first download all maven dependencies and then run the tests because it fails with hanging downloads otherwise.
        chown -R quattortest:quattortest .
        runuser --shell /bin/bash --preserve-environment --command "source /usr/bin/mvn_test.sh && mvn_run \"dependency:resolve-plugins dependency:go-offline\" && mvn_test" quattortest
